apiVersion: agents.example.io/v1alpha1
kind: Connector
metadata:
  name: slack
  labels:
    tier: base
    category: messaging
spec:
  runtime: node
  entry: "./connectors/slack/index.js"
  triggers:
    - type: http
      endpoint:
        path: /slack/events
        method: POST
  events:
    - name: slack.message
      properties:
        channelId:
          type: string
        userId:
          type: string
        teamId:
          type: string
        threadTs:
          type: string
        eventType:
          type: string
