apiVersion: agents.example.io/v1alpha1
kind: Connector
metadata:
  name: slack
  labels:
    tier: base
    category: messaging
spec:
  type: slack
  runtime: node
  entry: "./connectors/slack/index.js"
  triggers:
    - handler: onSlackEvent
