apiVersion: agents.example.io/v1alpha1
kind: Connector
metadata:
  name: cli
  labels:
    tier: base
    category: interactive
spec:
  runtime: node
  entry: "./connectors/cli/index.js"
  triggers:
    - type: cli
  events:
    - name: user_input
      properties:
        instanceKey:
          type: string
