apiVersion: agents.example.io/v1alpha1
kind: Extension
metadata:
  name: logging
  labels:
    category: observability
spec:
  runtime: node
  entry: "./extensions/logging/index.js"
  config:
    logLevel: "info"
    logDir: "./logs"
    includeTimestamp: true
    maxLogFileSizeMB: 10
