apiVersion: agents.example.io/v1alpha1
kind: Connector
metadata:
  name: telegram
  labels:
    tier: sample
spec:
  type: telegram

  # Bot Token 설정
  # 방법 1: 환경변수 (권장)
  botToken:
    valueFrom:
      env: "TELEGRAM_BOT_TOKEN"

  # 방법 2: 직접 값 (비권장, 테스트용)
  # botToken:
  #   value: "123456789:ABCDEF..."

  # Long Polling 설정
  polling:
    enabled: true
    timeout: 30

  # Webhook 설정 (polling과 배타적)
  # webhook:
  #   enabled: true
  #   url: "https://your-domain.com/webhook/telegram"
  #   secret: "your-webhook-secret"

  # 메시지 수신 규칙
  ingress:
    # /code 명령어로 코딩 에이전트 호출
    - match:
        command: "/code"
      route:
        swarmRef: { kind: Swarm, name: default }

    # /help 명령어
    - match:
        command: "/help"
      route:
        swarmRef: { kind: Swarm, name: default }

    # 그 외 모든 메시지 (봇이 멘션되거나 private chat인 경우)
    - route:
        swarmRef: { kind: Swarm, name: default }

  # 메시지 송신 설정
  egress:
    parseMode: Markdown
