apiVersion: agents.example.io/v1alpha1
kind: Connector
metadata:
  name: discord
  labels:
    tier: base
    category: messaging
spec:
  runtime: node
  entry: "./connectors/discord/index.js"
  triggers:
    - type: http
      endpoint:
        path: /discord/interactions
        method: POST
  events:
    - name: discord.message
      properties:
        channelId:
          type: string
        guildId:
          type: string
        userId:
          type: string
        username:
          type: string
        messageId:
          type: string
        timestamp:
          type: string
