apiVersion: agents.example.io/v1alpha1
kind: Connector
metadata:
  name: discord
  labels:
    tier: base
    category: messaging
spec:
  type: discord
  runtime: node
  entry: "./connectors/discord/index.js"
  triggers:
    - handler: onDiscordMessage
