apiVersion: agents.example.io/v1alpha1
kind: Tool
metadata:
  name: code
  labels:
    tier: sample
spec:
  runtime: node
  entry: "./dist/tools/code/index.js"
  errorMessageLimit: 2000

  exports:
    - name: code.read
      description: |
        파일을 읽어서 줄 번호와 함께 내용을 반환합니다.
        특정 줄 범위만 읽을 수도 있습니다.
      parameters:
        type: object
        properties:
          path:
            type: string
            description: "읽을 파일 경로"
          startLine:
            type: number
            description: "시작 줄 번호 (1부터 시작)"
          endLine:
            type: number
            description: "끝 줄 번호"
        required: [path]

    - name: code.write
      description: |
        파일을 생성하거나 수정합니다.
        디렉터리가 없으면 자동으로 생성합니다.
      parameters:
        type: object
        properties:
          path:
            type: string
            description: "파일 경로"
          content:
            type: string
            description: "파일 내용"
          createDirs:
            type: boolean
            description: "상위 디렉터리 자동 생성 (기본: true)"
        required: [path, content]

    - name: code.execute
      description: |
        코드를 실행하고 결과를 반환합니다.
        지원 언어: javascript, typescript, python, bash
        ⚠️ 주의: 신뢰할 수 있는 코드만 실행하세요.
      parameters:
        type: object
        properties:
          language:
            type: string
            enum: [javascript, typescript, python, bash]
            description: "프로그래밍 언어"
          code:
            type: string
            description: "실행할 코드"
          timeout:
            type: number
            description: "실행 제한 시간 (ms, 기본: 30000)"
        required: [language, code]

    - name: code.search
      description: |
        코드에서 패턴을 검색합니다 (grep).
        정규식 패턴을 지원합니다.
      parameters:
        type: object
        properties:
          pattern:
            type: string
            description: "검색할 패턴 (정규식)"
          path:
            type: string
            description: "검색 시작 경로 (기본: 현재 디렉터리)"
          filePattern:
            type: string
            description: "파일 패턴 (기본: *.{ts,js,py,java,go,rs})"
          maxResults:
            type: number
            description: "최대 결과 수 (기본: 50)"
        required: [pattern]

    - name: code.analyze
      description: |
        파일 또는 디렉터리의 코드를 분석합니다.
        구조, 의존성, 요약 정보를 제공합니다.
      parameters:
        type: object
        properties:
          path:
            type: string
            description: "분석할 파일 또는 디렉터리 경로"
          type:
            type: string
            enum: [structure, dependencies, summary]
            description: "분석 유형 (기본: summary)"
        required: [path]
