apiVersion: agents.example.io/v1alpha1
kind: Package
metadata:
  name: "@goondan/sample-telegram-coder"
  version: "0.0.1"
  annotations:
    description: "Telegram Bot Coding Agent Swarm Sample"
spec:
  dependencies:
    - "@goondan/base@0.0.1"
  resources:
    - goondan.yaml
