apiVersion: agents.example.io/v1alpha1
kind: Tool
metadata:
  name: text-transform
  labels:
    tier: base
    category: text
spec:
  runtime: node
  entry: "./tools/text-transform/index.js"
  errorMessageLimit: 2000
  exports:
    - name: text.template
      description: "Mustache-like 템플릿 문자열을 렌더링합니다. {{변수명}} 형태의 플레이스홀더를 값으로 치환합니다."
      parameters:
        type: object
        properties:
          template:
            type: string
            description: "템플릿 문자열 (예: 'Hello, {{name}}!')"
          variables:
            type: string
            description: "변수 JSON 문자열 (예: '{\"name\": \"World\"}')"
        required: ["template", "variables"]
    - name: text.regex
      description: "정규식을 사용하여 텍스트에서 매칭하거나 치환합니다."
      parameters:
        type: object
        properties:
          text:
            type: string
            description: "대상 텍스트"
          pattern:
            type: string
            description: "정규식 패턴"
          flags:
            type: string
            description: "정규식 플래그 (g, i, m 등, 기본값: '')"
          operation:
            type: string
            description: "작업 유형 (match: 매칭, replace: 치환, test: 존재 확인)"
            enum:
              - match
              - replace
              - test
          replacement:
            type: string
            description: "치환 문자열 (operation이 replace일 때 필수)"
        required: ["text", "pattern", "operation"]
    - name: text.format
      description: "텍스트 포맷을 변환합니다 (JSON, YAML, CSV 간 변환)."
      parameters:
        type: object
        properties:
          data:
            type: string
            description: "변환할 데이터 문자열"
          from:
            type: string
            description: "원본 포맷"
            enum:
              - json
              - yaml
              - csv
          to:
            type: string
            description: "대상 포맷"
            enum:
              - json
              - yaml
              - csv
        required: ["data", "from", "to"]
