# Compaction Extension Sample Bundle
# Demonstrates LLM conversation compaction strategies for context window management

apiVersion: agents.example.io/v1alpha1
kind: Model
metadata:
  name: gpt-4o
spec:
  provider: openai
  name: gpt-4o
  options:
    temperature: 0.7
    maxTokens: 4096

---

# Token-based compaction strategy
apiVersion: agents.example.io/v1alpha1
kind: Extension
metadata:
  name: compaction
  labels:
    tier: sample
spec:
  runtime: node
  entry: "./extensions/compaction/index.ts"
  config:
    strategy: token
    maxTokens: 8000
    preserveRecent: 5
    summaryPrompt: "Summarize the following conversation concisely, preserving key information and context:"
    enableLogging: true

---

# Alternative: Turn-based compaction
# apiVersion: agents.example.io/v1alpha1
# kind: Extension
# metadata:
#   name: compaction-turn
# spec:
#   runtime: node
#   entry: "./extensions/compaction/index.ts"
#   config:
#     strategy: turn
#     maxTurns: 20
#     preserveRecent: 5
#     enableLogging: true

---

# Alternative: Sliding window compaction
# apiVersion: agents.example.io/v1alpha1
# kind: Extension
# metadata:
#   name: compaction-sliding
# spec:
#   runtime: node
#   entry: "./extensions/compaction/index.ts"
#   config:
#     strategy: sliding
#     windowSize: 10
#     enableLogging: true

---

apiVersion: agents.example.io/v1alpha1
kind: Agent
metadata:
  name: main-agent
  labels:
    tier: demo
spec:
  modelConfig:
    modelRef: { kind: Model, name: gpt-4o }
  prompts:
    systemRef: "./prompts/default.system.md"
  extensions:
    - { kind: Extension, name: compaction }
  tools: []

---

apiVersion: agents.example.io/v1alpha1
kind: Swarm
metadata:
  name: compaction-demo
spec:
  entrypoint: { kind: Agent, name: main-agent }
  agents:
    - { kind: Agent, name: main-agent }

---

apiVersion: agents.example.io/v1alpha1
kind: Connector
metadata:
  name: cli
  labels:
    tier: base
    category: interactive
spec:
  runtime: node
  entry: "../../base/src/connectors/cli/index.ts"
  triggers:
    - type: cli
  events:
    - name: user_input

---

apiVersion: agents.example.io/v1alpha1
kind: Connection
metadata:
  name: cli-to-compaction-demo
spec:
  connectorRef: { kind: Connector, name: cli }
  ingress:
    rules:
      - route: {}
