apiVersion: agents.example.io/v1alpha1
kind: Package
metadata:
  name: "@goondan/sample-compaction"
  version: "0.0.1"
  annotations:
    description: "LLM 대화 Compaction Extension 데모"
spec:
  dependencies:
    - "@goondan/base"

---

# Compaction Extension Sample Bundle
# Demonstrates LLM conversation compaction strategies for context window management

apiVersion: agents.example.io/v1alpha1
kind: Model
metadata:
  name: gpt-4o
spec:
  provider: openai
  name: gpt-4o
  options:
    temperature: 0.7
    maxTokens: 4096

---

# Token-based compaction strategy
apiVersion: agents.example.io/v1alpha1
kind: Extension
metadata:
  name: compaction
  labels:
    tier: sample
spec:
  runtime: node
  entry: "./extensions/compaction/index.ts"
  config:
    strategy: token
    maxTokens: 8000
    preserveRecent: 5
    summaryPrompt: "Summarize the following conversation concisely, preserving key information and context:"
    enableLogging: true

---

apiVersion: agents.example.io/v1alpha1
kind: Agent
metadata:
  name: main-agent
  labels:
    tier: demo
spec:
  modelConfig:
    modelRef: { kind: Model, name: gpt-4o }
  prompts:
    systemRef: "./prompts/default.system.md"
  extensions:
    - { kind: Extension, name: compaction }
  tools: []

---

apiVersion: agents.example.io/v1alpha1
kind: Swarm
metadata:
  name: compaction-demo
spec:
  entrypoint: { kind: Agent, name: main-agent }
  agents:
    - { kind: Agent, name: main-agent }

---

apiVersion: agents.example.io/v1alpha1
kind: Connection
metadata:
  name: cli-to-compaction-demo
spec:
  connectorRef: { kind: Connector, name: cli, package: "@goondan/base" }
  ingress:
    rules:
      - route: {}
