apiVersion: goondan.ai/v1
kind: Package
metadata:
  name: "@samples/brain-persona"
spec:
  version: "0.1.0"
  dependencies:
    - name: "@goondan/base"
      version: "0.0.3-alpha17"
---
apiVersion: goondan.ai/v1
kind: Model
metadata:
  name: fast-model
spec:
  provider: anthropic
  model: claude-haiku-4-5
  apiKey:
    valueFrom:
      env: ANTHROPIC_API_KEY
---
apiVersion: goondan.ai/v1
kind: Model
metadata:
  name: default-model
spec:
  provider: anthropic
  model: claude-sonnet-4-5
  apiKey:
    valueFrom:
      env: ANTHROPIC_API_KEY
---
apiVersion: goondan.ai/v1
kind: Extension
metadata:
  name: worker-lifecycle
spec:
  entry: "./extensions/worker-lifecycle.ts"
---
apiVersion: goondan.ai/v1
kind: Extension
metadata:
  name: idle-monitor
spec:
  entry: "./extensions/idle-monitor.ts"
---
apiVersion: goondan.ai/v1
kind: Extension
metadata:
  name: date-helper
spec:
  entry: "./extensions/date-helper.ts"
---
apiVersion: goondan.ai/v1
kind: Agent
metadata:
  name: coordinator
spec:
  modelConfig:
    modelRef: "Model/fast-model"
  prompt:
    systemRef: "./prompts/coordinator.system.md"
  extensions:
    - ref:
        kind: Extension
        name: message-window
        package: "@goondan/base"
    - ref:
        kind: Extension
        name: message-compaction
        package: "@goondan/base"
    - ref:
        kind: Extension
        name: context-message
        package: "@goondan/base"
      config:
        includeAgentPrompt: true
        includeSwarmCatalog: true
    - ref: "Extension/idle-monitor"
  requiredTools:
    - "telegram__send"
    - "slack__send"
  tools:
    - ref:
        kind: Tool
        name: agents
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: telegram
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: slack
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: wait
        package: "@goondan/base"
    # watch 모드(--watch) 사용 시 불필요 — manifest 변경을 자동 감지하여 해당 에이전트만 restart
    - ref:
        kind: Tool
        name: self-restart
        package: "@goondan/base"
---
apiVersion: goondan.ai/v1
kind: Agent
metadata:
  name: worker
spec:
  modelConfig:
    modelRef: "Model/default-model"
  prompt:
    systemRef: "./prompts/worker.system.md"
  extensions:
    - ref:
        kind: Extension
        name: message-window
        package: "@goondan/base"
    - ref:
        kind: Extension
        name: context-message
        package: "@goondan/base"
    - ref: "Extension/worker-lifecycle"
    - ref: "Extension/date-helper"
  tools:
    - ref:
        kind: Tool
        name: agents
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: bash
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: file-system
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: http-fetch
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: json-query
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: text-transform
        package: "@goondan/base"
---
apiVersion: goondan.ai/v1
kind: Agent
metadata:
  name: unconscious
spec:
  modelConfig:
    modelRef: "Model/fast-model"
  prompt:
    systemRef: "./prompts/unconscious.system.md"
  extensions:
    - ref:
        kind: Extension
        name: message-window
        package: "@goondan/base"
    - ref:
        kind: Extension
        name: context-message
        package: "@goondan/base"
  tools:
    - ref:
        kind: Tool
        name: agents
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: file-system
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: bash
        package: "@goondan/base"
---
apiVersion: goondan.ai/v1
kind: Agent
metadata:
  name: observer
spec:
  modelConfig:
    modelRef: "Model/fast-model"
  prompt:
    systemRef: "./prompts/observer.system.md"
  extensions:
    - ref:
        kind: Extension
        name: message-window
        package: "@goondan/base"
    - ref:
        kind: Extension
        name: context-message
        package: "@goondan/base"
  tools:
    - ref:
        kind: Tool
        name: agents
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: file-system
        package: "@goondan/base"
---
apiVersion: goondan.ai/v1
kind: Agent
metadata:
  name: reflection
spec:
  modelConfig:
    modelRef: "Model/default-model"
  prompt:
    systemRef: "./prompts/reflection.system.md"
  extensions:
    - ref:
        kind: Extension
        name: message-window
        package: "@goondan/base"
    - ref:
        kind: Extension
        name: context-message
        package: "@goondan/base"
  tools:
    - ref:
        kind: Tool
        name: agents
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: file-system
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: bash
        package: "@goondan/base"
---
apiVersion: goondan.ai/v1
kind: Agent
metadata:
  name: dream
spec:
  modelConfig:
    modelRef: "Model/default-model"
  prompt:
    systemRef: "./prompts/dream.system.md"
  extensions:
    - ref:
        kind: Extension
        name: message-window
        package: "@goondan/base"
    - ref:
        kind: Extension
        name: context-message
        package: "@goondan/base"
  tools:
    - ref:
        kind: Tool
        name: agents
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: file-system
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: bash
        package: "@goondan/base"
---
apiVersion: goondan.ai/v1
kind: Swarm
metadata:
  name: brain
spec:
  entryAgent: "Agent/coordinator"
  agents:
    - ref: "Agent/coordinator"
    - ref: "Agent/worker"
    - ref: "Agent/unconscious"
    - ref: "Agent/observer"
    - ref: "Agent/reflection"
    - ref: "Agent/dream"
---
apiVersion: goondan.ai/v1
kind: Connection
metadata:
  name: telegram-to-brain
spec:
  connectorRef:
    kind: Connector
    name: telegram-polling
    package: "@goondan/base"
  swarmRef: "Swarm/brain"
  secrets:
    TELEGRAM_BOT_TOKEN:
      valueFrom:
        env: TELEGRAM_BOT_TOKEN
  ingress:
    rules:
      - match:
          event: telegram_message
        route:
          instanceKey: "brain-persona-shared"
---
apiVersion: goondan.ai/v1
kind: Connection
metadata:
  name: slack-to-brain
spec:
  connectorRef:
    kind: Connector
    name: slack
    package: "@goondan/base"
  swarmRef: "Swarm/brain"
  config:
    SLACK_WEBHOOK_PORT:
      value: "3102"
  ingress:
    rules:
      - match:
          event: message_im
        route:
          instanceKey: "brain-persona-shared"
      - match:
          event: app_mention
        route:
          instanceKey: "brain-persona-shared"
---
apiVersion: goondan.ai/v1
kind: Connection
metadata:
  name: cli-to-brain
spec:
  connectorRef:
    kind: Connector
    name: cli
    package: "@goondan/base"
  swarmRef: "Swarm/brain"
  ingress:
    rules:
      - match:
          event: stdin_message
        route:
          agentRef: "Agent/coordinator"
          instanceKey: "cli-test"
