apiVersion: goondan.ai/v1
kind: Package
metadata:
  name: "@samples/brain-persona"
spec:
  version: "0.1.0"
  dependencies:
    - name: "@goondan/base"
      version: "^1.0.3"
---
apiVersion: goondan.ai/v1
kind: Model
metadata:
  name: fast-model
spec:
  provider: anthropic
  model: claude-haiku-4-5
  apiKey:
    valueFrom:
      env: ANTHROPIC_API_KEY
---
apiVersion: goondan.ai/v1
kind: Model
metadata:
  name: default-model
spec:
  provider: anthropic
  model: claude-sonnet-4-5
  apiKey:
    valueFrom:
      env: ANTHROPIC_API_KEY
---
apiVersion: goondan.ai/v1
kind: Extension
metadata:
  name: context-injector
spec:
  entry: "./extensions/context-injector.mjs"
---
apiVersion: goondan.ai/v1
kind: Agent
metadata:
  name: coordinator
spec:
  modelConfig:
    modelRef: "Model/fast-model"
  prompts:
    systemRef: "./prompts/coordinator.system.md"
  extensions:
    - ref:
        kind: Extension
        name: message-window
        package: "@goondan/base"
    - ref:
        kind: Extension
        name: message-compaction
        package: "@goondan/base"
    - ref: "Extension/context-injector"
  requiredTools:
    - "telegram__send"
    - "slack__send"
  tools:
    - ref:
        kind: Tool
        name: agents
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: telegram
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: slack
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: self-restart
        package: "@goondan/base"
---
apiVersion: goondan.ai/v1
kind: Agent
metadata:
  name: researcher
spec:
  modelConfig:
    modelRef: "Model/default-model"
  prompts:
    systemRef: "./prompts/researcher.system.md"
  extensions:
    - ref:
        kind: Extension
        name: message-window
        package: "@goondan/base"
  tools:
    - ref:
        kind: Tool
        name: agents
        package: "@goondan/base"
---
apiVersion: goondan.ai/v1
kind: Agent
metadata:
  name: builder
spec:
  modelConfig:
    modelRef: "Model/default-model"
  prompts:
    systemRef: "./prompts/builder.system.md"
  extensions:
    - ref:
        kind: Extension
        name: message-window
        package: "@goondan/base"
  tools:
    - ref:
        kind: Tool
        name: agents
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: bash
        package: "@goondan/base"
    - ref:
        kind: Tool
        name: file-system
        package: "@goondan/base"
---
apiVersion: goondan.ai/v1
kind: Agent
metadata:
  name: reviewer
spec:
  modelConfig:
    modelRef: "Model/default-model"
  prompts:
    systemRef: "./prompts/reviewer.system.md"
  extensions:
    - ref:
        kind: Extension
        name: message-window
        package: "@goondan/base"
  tools:
    - ref:
        kind: Tool
        name: agents
        package: "@goondan/base"
---
apiVersion: goondan.ai/v1
kind: Swarm
metadata:
  name: brain
spec:
  entryAgent: "Agent/coordinator"
  agents:
    - ref: "Agent/coordinator"
    - ref: "Agent/researcher"
    - ref: "Agent/builder"
    - ref: "Agent/reviewer"
  policy:
    maxStepsPerTurn: 24
---
apiVersion: goondan.ai/v1
kind: Connection
metadata:
  name: telegram-to-brain
spec:
  connectorRef:
    kind: Connector
    name: telegram-polling
    package: "@goondan/base"
  swarmRef: "Swarm/brain"
  secrets:
    TELEGRAM_BOT_TOKEN:
      valueFrom:
        env: TELEGRAM_BOT_TOKEN
  ingress:
    rules:
      - match:
          event: telegram_message
        route:
          instanceKey: "brain-persona-shared"
---
apiVersion: goondan.ai/v1
kind: Connection
metadata:
  name: slack-to-brain
spec:
  connectorRef:
    kind: Connector
    name: slack
    package: "@goondan/base"
  swarmRef: "Swarm/brain"
  config:
    SLACK_WEBHOOK_PORT:
      value: "8787"
  ingress:
    rules:
      - match:
          event: message_im
        route:
          instanceKey: "brain-persona-shared"
      - match:
          event: app_mention
        route:
          instanceKey: "brain-persona-shared"
