apiVersion: agents.example.io/v1alpha1
kind: Connector
metadata:
  name: telegram
  labels:
    tier: base
    category: messaging
spec:
  type: telegram
  runtime: node
  entry: "./connectors/telegram/index.js"
  triggers:
    - handler: onUpdate
