apiVersion: agents.example.io/v1alpha1
kind: Connector
metadata:
  name: telegram
  labels:
    tier: base
    category: messaging
spec:
  runtime: node
  entry: "./connectors/telegram/index.js"
  triggers:
    - type: http
      endpoint:
        path: /telegram/webhook
        method: POST
  events:
    - name: telegram.message
      properties:
        chatId:
          type: string
        userId:
          type: string
        chatType:
          type: string
        messageId:
          type: number
