apiVersion: agents.example.io/v1alpha1
kind: Package
metadata:
  name: "@goondan/sample-package-consumer"
  version: "0.0.1"
  annotations:
    description: "coding-swarm 패키지를 의존성으로 사용하는 예제"
spec:
  dependencies:
    - "file:../sample-1-coding-swarm"
    - "@goondan/base"

---

# Package Consumer Sample
# coding-swarm 패키지의 리소스를 사용하고 커스터마이징하는 예제
#
# 이 샘플은 패키지 시스템의 다음 기능을 시연합니다:
# 1. 외부 패키지의 리소스 참조
# 2. 프롬프트 오버라이드
# 3. 새로운 Agent 추가
# 4. 커스텀 Connector 설정

# 커스텀 Agent - coding-swarm 패키지의 도구를 활용하되 프롬프트를 커스터마이징
apiVersion: agents.example.io/v1alpha1
kind: Agent
metadata:
  name: assistant
  labels:
    role: general
spec:
  modelConfig:
    # coding-swarm 패키지의 모델 참조
    modelRef: { kind: Model, name: default-model }
    params:
      temperature: 0.7
      maxTokens: 4096
  prompts:
    # 커스텀 프롬프트 사용
    systemRef: "./prompts/custom.system.md"
  tools:
    - { kind: Tool, name: file-system, package: "@goondan/base" }
    - { kind: Tool, name: agents, package: "@goondan/base" }

---

# 커스텀 Swarm - 패키지의 에이전트와 새 에이전트 조합
apiVersion: agents.example.io/v1alpha1
kind: Swarm
metadata:
  name: custom-swarm
  labels:
    purpose: custom
spec:
  # 새로 정의한 assistant를 진입점으로 사용
  entrypoint: { kind: Agent, name: assistant }
  agents:
    - { kind: Agent, name: assistant }
    # coding-swarm 패키지의 에이전트도 포함
    - { kind: Agent, name: planner }
    - { kind: Agent, name: coder }
  policy:
    maxStepsPerTurn: 30

---

apiVersion: agents.example.io/v1alpha1
kind: Connection
metadata:
  name: cli-to-custom-swarm
spec:
  connectorRef: { kind: Connector, name: cli, package: "@goondan/base" }
  ingress:
    rules:
      - route: {}
