apiVersion: agents.example.io/v1alpha1
kind: Package
metadata:
  name: "@goondan/sample-devops-assistant"
  version: "0.0.1"
  annotations:
    description: "DevOps 지원 에이전트 (bash + logging)"
spec:
  dependencies:
    - "@goondan/base"

---

# Goondan DevOps Assistant Sample
# DevOps 지원 에이전트 스웜 - devops(명령 실행/진단) + planner(작업 계획)
apiVersion: agents.example.io/v1alpha1
kind: Model
metadata:
  name: default-model
  labels:
    provider: anthropic
spec:
  provider: anthropic
  name: claude-sonnet-4-5

---

# DevOps Agent - 시스템 명령 실행 및 진단
apiVersion: agents.example.io/v1alpha1
kind: Agent
metadata:
  name: devops
  labels:
    role: executor
    specialty: operations
spec:
  modelConfig:
    modelRef: { kind: Model, name: default-model }
    params:
      temperature: 0.2
      maxTokens: 4096
  prompts:
    systemRef: "./prompts/devops.md"
  tools:
    - { kind: Tool, name: bash, package: "@goondan/base" }
    - { kind: Tool, name: agents, package: "@goondan/base" }
  extensions:
    - { kind: Extension, name: logging, package: "@goondan/base" }

---

# Planner Agent - 작업 계획 및 분석
apiVersion: agents.example.io/v1alpha1
kind: Agent
metadata:
  name: planner
  labels:
    role: orchestrator
    specialty: planning
spec:
  modelConfig:
    modelRef: { kind: Model, name: default-model }
    params:
      temperature: 0.3
      maxTokens: 4096
  prompts:
    systemRef: "./prompts/planner.md"
  tools:
    - { kind: Tool, name: agents, package: "@goondan/base" }
  extensions:
    - { kind: Extension, name: logging, package: "@goondan/base" }

---

# DevOps Swarm
apiVersion: agents.example.io/v1alpha1
kind: Swarm
metadata:
  name: devops-swarm
spec:
  entrypoint: { kind: Agent, name: devops }
  agents:
    - { kind: Agent, name: devops }
    - { kind: Agent, name: planner }
  policy:
    maxStepsPerTurn: 25

---

apiVersion: agents.example.io/v1alpha1
kind: Connection
metadata:
  name: cli-to-devops
spec:
  connectorRef: { kind: Connector, name: cli, package: "@goondan/base" }
  swarmRef: { kind: Swarm, name: devops-swarm }
  ingress:
    rules:
      - route: {}
