apiVersion: agents.example.io/v1alpha1
kind: Tool
metadata:
  name: file-system
  labels:
    tier: base
    category: filesystem
spec:
  runtime: node
  entry: "./tools/file-system/index.js"
  errorMessageLimit: 2000
  exports:
    - name: fs.read
      description: "파일의 내용을 읽어 반환합니다."
      parameters:
        type: object
        properties:
          path:
            type: string
            description: "읽을 파일의 경로"
          encoding:
            type: string
            description: "인코딩 (기본값: utf-8)"
        required: ["path"]
    - name: fs.write
      description: "파일에 내용을 기록합니다. 디렉토리가 없으면 자동 생성합니다."
      parameters:
        type: object
        properties:
          path:
            type: string
            description: "쓸 파일의 경로"
          content:
            type: string
            description: "파일에 기록할 내용"
          mode:
            type: string
            description: "쓰기 모드 (overwrite: 덮어쓰기, append: 추가, 기본값: overwrite)"
            enum:
              - overwrite
              - append
        required: ["path", "content"]
    - name: fs.list
      description: "디렉토리 내의 파일/폴더 목록을 반환합니다."
      parameters:
        type: object
        properties:
          path:
            type: string
            description: "조회할 디렉토리 경로"
          recursive:
            type: boolean
            description: "하위 디렉토리까지 재귀적으로 조회 (기본값: false)"
        required: ["path"]
    - name: fs.exists
      description: "파일 또는 디렉토리의 존재 여부를 확인합니다."
      parameters:
        type: object
        properties:
          path:
            type: string
            description: "확인할 경로"
        required: ["path"]
