# Goondan Sample 3: Multi-Agent Telegram Bot
# 라우터 에이전트가 전문 에이전트들에게 작업을 위임하는 멀티 에이전트 시스템
apiVersion: agents.example.io/v1alpha1
kind: Model
metadata:
  name: default-model
spec:
  provider: anthropic
  name: claude-sonnet-4-5

---
# 라우터 에이전트: 사용자 요청을 분석하고 적절한 에이전트에게 위임
apiVersion: agents.example.io/v1alpha1
kind: Agent
metadata:
  name: router
spec:
  modelConfig:
    modelRef: { kind: Model, name: default-model }
    params:
      temperature: 0.3
      maxTokens: 4096

  prompts:
    systemRef: "./prompts/router.system.md"

  tools:
    # 위임 도구
    - { kind: Tool, name: delegate }
    # 코드 읽기 (컨텍스트 파악용)
    - { kind: Tool, name: code }

  extensions:
    - { kind: Extension, name: compaction }

---
# 코더 에이전트: 코드 작성 및 수정 전문
apiVersion: agents.example.io/v1alpha1
kind: Agent
metadata:
  name: coder
spec:
  modelConfig:
    modelRef: { kind: Model, name: default-model }
    params:
      temperature: 0.2
      maxTokens: 8192

  prompts:
    systemRef: "./prompts/coder.system.md"

  tools:
    - { kind: Tool, name: code }
    - { kind: Tool, name: git }
    - { kind: Tool, name: delegate }

  extensions:
    - { kind: Extension, name: compaction }

---
# 리뷰어 에이전트: 코드 리뷰 및 품질 검사 전문
apiVersion: agents.example.io/v1alpha1
kind: Agent
metadata:
  name: reviewer
spec:
  modelConfig:
    modelRef: { kind: Model, name: default-model }
    params:
      temperature: 0.4
      maxTokens: 4096

  prompts:
    systemRef: "./prompts/reviewer.system.md"

  tools:
    - { kind: Tool, name: code }
    - { kind: Tool, name: git }
    - { kind: Tool, name: delegate }

  extensions:
    - { kind: Extension, name: compaction }

---
# 문서화 에이전트: 문서 작성 전문
apiVersion: agents.example.io/v1alpha1
kind: Agent
metadata:
  name: docs
spec:
  modelConfig:
    modelRef: { kind: Model, name: default-model }
    params:
      temperature: 0.5
      maxTokens: 4096

  prompts:
    systemRef: "./prompts/docs.system.md"

  tools:
    - { kind: Tool, name: code }
    - { kind: Tool, name: git }
    - { kind: Tool, name: delegate }

  extensions:
    - { kind: Extension, name: compaction }

---
# 멀티 에이전트 스웜
apiVersion: agents.example.io/v1alpha1
kind: Swarm
metadata:
  name: default
spec:
  # 라우터가 진입점
  entrypoint: { kind: Agent, name: router }

  # 모든 에이전트 포함
  agents:
    - { kind: Agent, name: router }
    - { kind: Agent, name: coder }
    - { kind: Agent, name: reviewer }
    - { kind: Agent, name: docs }

  policy:
    maxStepsPerTurn: 24

