apiVersion: agents.example.io/v1alpha1
kind: Tool
metadata:
  name: bash
  labels:
    tier: system
spec:
  runtime: node
  entry: "./tools/bash/index.js"
  errorMessageLimit: 2000
  exports:
    - name: bash.exec
      description: "bash 명령어를 실행합니다"
      parameters:
        type: object
        properties:
          command:
            type: string
            description: "실행할 bash 명령어"
          timeout:
            type: number
            description: "타임아웃 (ms, 기본값: 30000)"
          cwd:
            type: string
            description: "작업 디렉토리"
        required: ["command"]
