# Goondan Web Researcher Sample
# 웹 리서치 에이전트 스웜 - researcher(정보 수집) + summarizer(결과 요약)
apiVersion: agents.example.io/v1alpha1
kind: Model
metadata:
  name: default-model
  labels:
    provider: anthropic
spec:
  provider: anthropic
  name: claude-sonnet-4-5

---

# HTTP Fetch Tool - 웹 페이지/API 호출
apiVersion: agents.example.io/v1alpha1
kind: Tool
metadata:
  name: http-fetch
  labels:
    tier: base
    category: network
spec:
  runtime: node
  entry: "./tools/http-fetch/index.ts"
  errorMessageLimit: 2000
  exports:
    - name: http.get
      description: "HTTP GET 요청을 실행하고 응답을 반환합니다. 웹 페이지 내용이나 API 데이터를 가져올 때 사용합니다."
      parameters:
        type: object
        properties:
          url:
            type: string
            description: "요청할 URL"
          headers:
            type: object
            description: "요청 헤더 (key-value)"
          timeout:
            type: number
            description: "타임아웃 (ms, 기본값: 30000)"
        required: ["url"]
    - name: http.post
      description: "HTTP POST 요청을 실행하고 응답을 반환합니다. API 호출이나 검색 요청에 사용합니다."
      parameters:
        type: object
        properties:
          url:
            type: string
            description: "요청할 URL"
          body:
            type: string
            description: "요청 본문 (JSON 문자열)"
          headers:
            type: object
            description: "요청 헤더 (key-value)"
          timeout:
            type: number
            description: "타임아웃 (ms, 기본값: 30000)"
        required: ["url"]

---

# JSON Query Tool - 응답 데이터 파싱/추출
apiVersion: agents.example.io/v1alpha1
kind: Tool
metadata:
  name: json-query
  labels:
    tier: base
    category: data
spec:
  runtime: node
  entry: "./tools/json-query/index.ts"
  errorMessageLimit: 2000
  exports:
    - name: json.query
      description: "JSON 데이터에서 JSONPath 표현식으로 값을 추출합니다. API 응답에서 필요한 데이터를 선택적으로 가져올 때 사용합니다."
      parameters:
        type: object
        properties:
          data:
            type: string
            description: "JSON 문자열"
          path:
            type: string
            description: "JSONPath 표현식 (예: $.store.book[0].title, $.items[*].name)"
        required: ["data", "path"]
    - name: json.transform
      description: "JSON 데이터를 변환합니다. pick(필드 선택), omit(필드 제거), flatten(배열 평탄화) 등을 지원합니다."
      parameters:
        type: object
        properties:
          data:
            type: string
            description: "JSON 문자열"
          operation:
            type: string
            description: "변환 작업"
            enum:
              - pick
              - omit
              - flatten
              - keys
              - values
              - entries
              - merge
          fields:
            type: array
            items:
              type: string
            description: "대상 필드 목록 (pick, omit에서 사용)"
          mergeData:
            type: string
            description: "병합할 JSON 문자열 (merge에서 사용)"
        required: ["data", "operation"]

---

# Delegate Tool - 에이전트 간 작업 위임
apiVersion: agents.example.io/v1alpha1
kind: Tool
metadata:
  name: delegate-tool
  labels:
    tier: base
    category: orchestration
spec:
  runtime: node
  entry: "./tools/delegate/index.ts"
  exports:
    - name: agent.delegate
      description: "다른 에이전트에게 작업을 위임합니다. 수집한 정보를 요약 에이전트에게 전달할 때 사용합니다."
      parameters:
        type: object
        properties:
          agentName:
            type: string
            description: "위임할 에이전트의 이름"
            enum:
              - summarizer
          task:
            type: string
            description: "에이전트에게 전달할 작업 내용"
          context:
            type: string
            description: "작업 수행에 필요한 추가 컨텍스트 (수집한 원본 데이터 등)"
        required:
          - agentName
          - task
        additionalProperties: false

---

# Researcher Agent - 웹 정보 수집 및 분석
apiVersion: agents.example.io/v1alpha1
kind: Agent
metadata:
  name: researcher
  labels:
    role: orchestrator
    specialty: research
spec:
  modelConfig:
    modelRef: { kind: Model, name: default-model }
    params:
      temperature: 0.3
      maxTokens: 4096
  prompts:
    systemRef: "./prompts/researcher.md"
  tools:
    - { kind: Tool, name: http-fetch }
    - { kind: Tool, name: json-query }
    - { kind: Tool, name: delegate-tool }

---

# Summarizer Agent - 수집된 정보 요약 및 정리
apiVersion: agents.example.io/v1alpha1
kind: Agent
metadata:
  name: summarizer
  labels:
    role: executor
    specialty: summarization
spec:
  modelConfig:
    modelRef: { kind: Model, name: default-model }
    params:
      temperature: 0.4
      maxTokens: 4096
  prompts:
    systemRef: "./prompts/summarizer.md"

---

# Web Research Swarm
apiVersion: agents.example.io/v1alpha1
kind: Swarm
metadata:
  name: web-research-swarm
spec:
  entrypoint: { kind: Agent, name: researcher }
  agents:
    - { kind: Agent, name: researcher }
    - { kind: Agent, name: summarizer }
  policy:
    maxStepsPerTurn: 30

---

# CLI Connector
apiVersion: agents.example.io/v1alpha1
kind: Connector
metadata:
  name: cli
spec:
  type: cli

---

apiVersion: agents.example.io/v1alpha1
kind: Connection
metadata:
  name: cli-to-web-research
spec:
  connectorRef: { kind: Connector, name: cli }
  rules:
    - route:
        swarmRef: { kind: Swarm, name: web-research-swarm }
        instanceKeyFrom: "$.instanceKey"
        inputFrom: "$.text"
