apiVersion: agents.example.io/v1alpha1
kind: Package
metadata:
  name: "@goondan/sample-web-researcher"
  version: "0.0.1"
  annotations:
    description: "Web Researcher Sample"
spec:
  dependencies:
    - "@goondan/base"
  resources:
    - goondan.yaml
