import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = join(__dirname, '..', 'dist');
const outFile = join(__dirname, '..', '..', 'cli', 'src', 'studio', 'assets.ts');

if (!existsSync(distDir)) {
  console.error('dist/ not found. Run "vite build" first.');
  process.exit(1);
}

let html = readFileSync(join(distDir, 'index.html'), 'utf-8');

// Remove modulepreload links (content will be inlined)
html = html.replace(/<link\s+[^>]*rel="modulepreload"[^>]*\/?>/g, '');

// Inline CSS: <link rel="stylesheet" ... href="/assets/xxx.css">
html = html.replace(
  /<link\s+[^>]*href="([^"]+\.css)"[^>]*\/?>/g,
  (_match, href) => {
    const filePath = join(distDir, href);
    if (!existsSync(filePath)) {
      console.warn(`CSS file not found: ${href}`);
      return '';
    }
    const css = readFileSync(filePath, 'utf-8');
    return `<style>${css}</style>`;
  },
);

// Inline JS: <script type="module" ... src="/assets/xxx.js"></script>
html = html.replace(
  /<script\s+([^>]*)src="([^"]+\.js)"([^>]*)><\/script>/g,
  (_match, pre, src, post) => {
    const filePath = join(distDir, src);
    if (!existsSync(filePath)) {
      console.warn(`JS file not found: ${src}`);
      return '';
    }
    const js = readFileSync(filePath, 'utf-8');
    const hasModule = (pre + post).includes('type="module"');
    return `<script${hasModule ? ' type="module"' : ''}>${js}</script>`;
  },
);

// Clean up blank lines left from removed tags
html = html.replace(/^\s*\n/gm, '');

// Escape for TypeScript template literal
const escaped = html
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${');

const output = `// Auto-generated by @goondan/studio build — do not edit.\nexport const STUDIO_HTML = \`${escaped}\`;\n`;

writeFileSync(outFile, output, 'utf-8');
console.log('✓ Embedded studio assets →', outFile);
