apiVersion: agents.example.io/v1alpha1
kind: Tool
metadata:
  name: git
  labels:
    tier: sample
spec:
  runtime: node
  entry: "./dist/tools/git/index.js"
  errorMessageLimit: 2000

  exports:
    - name: git.status
      description: |
        Git 저장소의 현재 상태를 확인합니다.
        브랜치, 스테이지된 파일, 수정된 파일, 추적되지 않는 파일 목록을 반환합니다.
      parameters:
        type: object
        properties: {}

    - name: git.diff
      description: |
        변경 사항을 확인합니다.
        staged 옵션으로 스테이지된 변경만 볼 수 있습니다.
      parameters:
        type: object
        properties:
          staged:
            type: boolean
            description: "스테이지된 변경 사항만 표시 (기본: false)"
          file:
            type: string
            description: "특정 파일의 변경 사항만 표시"

    - name: git.log
      description: |
        커밋 로그를 조회합니다.
      parameters:
        type: object
        properties:
          limit:
            type: number
            description: "표시할 커밋 수 (기본: 10)"
          oneline:
            type: boolean
            description: "한 줄 형식으로 표시"
          branch:
            type: string
            description: "특정 브랜치의 로그"

    - name: git.commit
      description: |
        변경 사항을 커밋합니다.
        ⚠️ 주의: 커밋 전에 변경 내용을 확인하세요.
      parameters:
        type: object
        properties:
          message:
            type: string
            description: "커밋 메시지"
          files:
            type: array
            items:
              type: string
            description: "커밋할 파일 목록 (지정하지 않으면 스테이지된 파일만)"
          all:
            type: boolean
            description: "모든 변경 사항 커밋 (-A 옵션)"
        required: [message]

    - name: git.branch
      description: |
        브랜치를 관리합니다.
        list, create, checkout, delete 작업을 지원합니다.
      parameters:
        type: object
        properties:
          action:
            type: string
            enum: [list, create, checkout, delete]
            description: "브랜치 작업 (기본: list)"
          name:
            type: string
            description: "브랜치 이름 (create, checkout, delete에 필요)"
