apiVersion: agents.example.io/v1alpha1
kind: Tool
metadata:
  name: filesystem
  labels:
    tier: sample
spec:
  runtime: node
  entry: "./dist/tools/filesystem/index.js"
  errorMessageLimit: 1500
  exports:
    - name: fs.list
      description: |
        디렉터리의 파일/폴더 목록을 조회합니다.
        결과는 디렉터리 우선, 이름순으로 정렬됩니다.
      parameters:
        type: object
        properties:
          path:
            type: string
            description: "조회할 디렉터리 경로 (기본: 현재 디렉터리)"
          showHidden:
            type: boolean
            description: "숨김 파일(. 으로 시작) 표시 여부 (기본: false)"
          sortBy:
            type: string
            enum: [name, size, modified]
            description: "정렬 기준 (기본: name)"
    - name: fs.stat
      description: |
        파일 또는 디렉터리의 상세 정보를 조회합니다.
        크기, 권한, 생성/수정 시간 등을 확인할 수 있습니다.
      parameters:
        type: object
        properties:
          path:
            type: string
            description: "조회할 파일/디렉터리 경로"
        required: [path]
    - name: fs.tree
      description: |
        디렉터리의 트리 구조를 시각적으로 출력합니다.
        depth를 조절하여 깊이를 제한할 수 있습니다.
      parameters:
        type: object
        properties:
          path:
            type: string
            description: "조회할 디렉터리 경로 (기본: 현재 디렉터리)"
          maxDepth:
            type: number
            description: "최대 탐색 깊이 (기본: 3)"
          showHidden:
            type: boolean
            description: "숨김 파일 표시 여부 (기본: false)"
    - name: fs.search
      description: |
        파일명 패턴으로 파일을 검색합니다.
        * (모든 문자), ? (단일 문자) 와일드카드를 지원합니다.
      parameters:
        type: object
        properties:
          pattern:
            type: string
            description: "검색 패턴 (예: *.ts, package*, test?.js)"
          path:
            type: string
            description: "검색 시작 경로 (기본: 현재 디렉터리)"
          maxDepth:
            type: number
            description: "최대 검색 깊이 (기본: 5)"
          maxResults:
            type: number
            description: "최대 결과 수 (기본: 50)"
        required: [pattern]
