apiVersion: agents.example.io/v1alpha1
kind: Tool
metadata:
  name: agents
  labels:
    tier: core
    category: orchestration
spec:
  runtime: node
  entry: "./tools/agents/index.js"
  exports:
    - name: agents.delegate
      description: "다른 에이전트에 작업을 위임합니다. 새 에이전트 인스턴스를 생성하여 블로킹 실행 후 결과를 반환합니다."
      parameters:
        type: object
        properties:
          agentName:
            type: string
            description: "위임할 에이전트 이름"
          task:
            type: string
            description: "에이전트에게 전달할 작업 내용"
          context:
            type: string
            description: "추가 컨텍스트 (선택)"
          async:
            type: boolean
            description: "true면 비동기 실행 (응답 대기 안함)"
        required:
          - agentName
          - task
    - name: agents.spawnInstance
      description: "에이전트 이름으로 새 인스턴스를 생성합니다. Turn 실행 없이 인스턴스만 생성하여 instanceId를 반환합니다."
      parameters:
        type: object
        properties:
          agentName:
            type: string
            description: "생성할 에이전트 이름"
        required:
          - agentName
    - name: agents.delegateToInstance
      description: "특정 인스턴스 ID의 에이전트에 작업을 위임합니다."
      parameters:
        type: object
        properties:
          instanceId:
            type: string
            description: "대상 에이전트 인스턴스 ID"
          task:
            type: string
            description: "에이전트에게 전달할 작업 내용"
          context:
            type: string
            description: "추가 컨텍스트 (선택)"
          async:
            type: boolean
            description: "true면 비동기 실행 (응답 대기 안함)"
        required:
          - instanceId
          - task
    - name: agents.destroyInstance
      description: "인스턴스 ID로 에이전트 인스턴스를 삭제합니다."
      parameters:
        type: object
        properties:
          instanceId:
            type: string
            description: "삭제할 에이전트 인스턴스 ID"
        required:
          - instanceId
    - name: agents.listInstances
      description: "현재 Swarm 내 에이전트 인스턴스 목록을 조회합니다."
      parameters:
        type: object
        properties: {}
