apiVersion: agents.example.io/v1alpha1
kind: Package
metadata:
  name: "@goondan/sample-coding-swarm"
  version: "0.0.1"
  annotations:
    description: "Planner-Coder-Reviewer 코딩 에이전트 스웜"
spec:
  dependencies:
    - "@goondan/base"

---

# Goondan Coding Swarm Sample
# Planner -> Coder -> Reviewer 구조의 코딩 에이전트 스웜
apiVersion: agents.example.io/v1alpha1
kind: Model
metadata:
  name: default-model
  labels:
    provider: anthropic
spec:
  provider: anthropic
  name: claude-sonnet-4-5

---

# File Tool - 파일 읽기/쓰기 도구
apiVersion: agents.example.io/v1alpha1
kind: Tool
metadata:
  name: file-toolkit
  labels:
    tier: base
    category: filesystem
spec:
  runtime: node
  entry: "./tools/file/index.ts"
  errorMessageLimit: 2000
  exports:
    - name: file.read
      description: "지정된 경로의 파일 내용을 읽어 반환합니다."
      parameters:
        type: object
        properties:
          path:
            type: string
            description: "읽을 파일의 경로"
        required:
          - path
        additionalProperties: false

    - name: file.write
      description: "지정된 경로에 파일을 생성하거나 덮어씁니다."
      parameters:
        type: object
        properties:
          path:
            type: string
            description: "쓸 파일의 경로"
          content:
            type: string
            description: "파일에 쓸 내용"
        required:
          - path
          - content
        additionalProperties: false

    - name: file.list
      description: "지정된 디렉토리의 파일 목록을 반환합니다."
      parameters:
        type: object
        properties:
          path:
            type: string
            description: "목록을 조회할 디렉토리 경로"
          recursive:
            type: boolean
            description: "하위 디렉토리까지 재귀적으로 조회할지 여부"
            default: false
        required:
          - path
        additionalProperties: false

---

# Planner Agent - 작업 계획 수립
apiVersion: agents.example.io/v1alpha1
kind: Agent
metadata:
  name: planner
  labels:
    role: orchestrator
spec:
  modelConfig:
    modelRef: { kind: Model, name: default-model }
    params:
      temperature: 0.3
      maxTokens: 4096
  prompts:
    systemRef: "./prompts/planner.system.md"
  tools:
    - { kind: Tool, name: file-toolkit }
    - { kind: Tool, name: agents, package: "@goondan/base" }

---

# Coder Agent - 코드 작성/수정
apiVersion: agents.example.io/v1alpha1
kind: Agent
metadata:
  name: coder
  labels:
    role: executor
spec:
  modelConfig:
    modelRef: { kind: Model, name: default-model }
    params:
      temperature: 0.5
      maxTokens: 8192
  prompts:
    systemRef: "./prompts/coder.system.md"
  tools:
    - { kind: Tool, name: file-toolkit }
    - { kind: Tool, name: agents, package: "@goondan/base" }

---

# Reviewer Agent - 코드 리뷰 및 품질 검증
apiVersion: agents.example.io/v1alpha1
kind: Agent
metadata:
  name: reviewer
  labels:
    role: validator
spec:
  modelConfig:
    modelRef: { kind: Model, name: default-model }
    params:
      temperature: 0.2
      maxTokens: 4096
  prompts:
    systemRef: "./prompts/reviewer.system.md"
  tools:
    - { kind: Tool, name: file-toolkit }
    - { kind: Tool, name: agents, package: "@goondan/base" }

---

# Coding Swarm - 에이전트 집합 정의
apiVersion: agents.example.io/v1alpha1
kind: Swarm
metadata:
  name: coding-swarm
  labels:
    purpose: coding
spec:
  entrypoint: { kind: Agent, name: planner }
  agents:
    - { kind: Agent, name: planner }
    - { kind: Agent, name: coder }
    - { kind: Agent, name: reviewer }
  policy:
    maxStepsPerTurn: 50

---

apiVersion: agents.example.io/v1alpha1
kind: Connection
metadata:
  name: cli-to-coding-swarm
spec:
  connectorRef: { kind: Connector, name: cli, package: "@goondan/base" }
  swarmRef: { kind: Swarm, name: coding-swarm }
  ingress:
    rules:
      - route: {}
