apiVersion: agents.example.io/v1alpha1
kind: Package
metadata:
  name: "@goondan/sample-coding-swarm"
  version: "0.0.1"
  annotations:
    description: "Planner-Coder-Reviewer 코딩 에이전트 스웜"
spec:
  dependencies:
    - "@goondan/base"

---

# Goondan Coding Swarm Sample
# Planner -> Coder -> Reviewer 구조의 코딩 에이전트 스웜
apiVersion: agents.example.io/v1alpha1
kind: Model
metadata:
  name: default-model
  labels:
    provider: anthropic
spec:
  provider: anthropic
  name: claude-sonnet-4-5

---

# Planner Agent - 작업 계획 수립
apiVersion: agents.example.io/v1alpha1
kind: Agent
metadata:
  name: planner
  labels:
    role: orchestrator
spec:
  modelConfig:
    modelRef: { kind: Model, name: default-model }
    params:
      temperature: 0.3
      maxTokens: 4096
  prompts:
    systemRef: "./prompts/planner.system.md"
  tools:
    - { kind: Tool, name: file-system, package: "@goondan/base" }
    - { kind: Tool, name: agents, package: "@goondan/base" }

---

# Coder Agent - 코드 작성/수정
apiVersion: agents.example.io/v1alpha1
kind: Agent
metadata:
  name: coder
  labels:
    role: executor
spec:
  modelConfig:
    modelRef: { kind: Model, name: default-model }
    params:
      temperature: 0.5
      maxTokens: 8192
  prompts:
    systemRef: "./prompts/coder.system.md"
  tools:
    - { kind: Tool, name: file-system, package: "@goondan/base" }
    - { kind: Tool, name: bash, package: "@goondan/base" }
    - { kind: Tool, name: agents, package: "@goondan/base" }

---

# Reviewer Agent - 코드 리뷰 및 품질 검증
apiVersion: agents.example.io/v1alpha1
kind: Agent
metadata:
  name: reviewer
  labels:
    role: validator
spec:
  modelConfig:
    modelRef: { kind: Model, name: default-model }
    params:
      temperature: 0.2
      maxTokens: 4096
  prompts:
    systemRef: "./prompts/reviewer.system.md"
  tools:
    - { kind: Tool, name: file-system, package: "@goondan/base" }
    - { kind: Tool, name: agents, package: "@goondan/base" }

---

# Coding Swarm - 에이전트 집합 정의
apiVersion: agents.example.io/v1alpha1
kind: Swarm
metadata:
  name: coding-swarm
  labels:
    purpose: coding
spec:
  entrypoint: { kind: Agent, name: planner }
  agents:
    - { kind: Agent, name: planner }
    - { kind: Agent, name: coder }
    - { kind: Agent, name: reviewer }
  policy:
    maxStepsPerTurn: 50

---

apiVersion: agents.example.io/v1alpha1
kind: Connection
metadata:
  name: cli-to-coding-swarm
spec:
  connectorRef: { kind: Connector, name: cli, package: "@goondan/base" }
  ingress:
    rules:
      - route: {}
